[package]
name = "ssw"
version = "1.1.0"
edition = "2021"
default-run = "ssw"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "release_script"
test = false
bench = false

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.0", features = ["derive"] }
dunce = "1.0"
duration-string = "0.1"
flate2 = "1.0"
futures = "0.3"
glob = "0.3.0"
lazy_static = "1.4"
log = "0.4"
regex = "1.7"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = { version = "0.12", features = ["paris", "termcolor"] }
time = { version = "0.3", features = ["formatting", "macros"] }
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
toml = "0.5"
which = "4.3"
zip = "0.6"

[target.'cfg(not(windows))'.dependencies]
dirs = "4.0"
