[package]
name = "ssw"
version = "2.0.0"
edition = "2021"
default-run = "ssw"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "release_script"
test = false
bench = false

[dependencies]
chrono = { version = "0.4.24", features = ["serde"] }
dirs = "5.0.0"
flate2 = "1.0.25"
getset = "0.1.2"
log = "0.4.17"
simplelog = { version = "0.12.1", features = ["paris"] }
thiserror = "1.0.40"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.8"
