[package]
name = "ssw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.22", features = ["serde"] }
dunce = "1.0.2"
flate2 = "1.0.24"
futures = "0.3.24"
log = "0.4.17"
regex = "1.6.0"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
simplelog = { version = "0.12.0", features = ["paris", "termcolor"] }
time = { version = "0.3.14", features = ["formatting", "macros"] }
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.4"
which = "4.3.0"

[target.'cfg(target_os = "linux")'.dependencies]
dirs = "4.0.0"

