[package]
name = "ssw"
version = "2.0.0"
edition = "2021"
default-run = "ssw"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "release_script"
test = false
bench = false

[dependencies]
tokio = { version = "1", features = ["full"] }
