[package]
name = "ssw"
version = "1.3.0"
edition = "2021"
default-run = "ssw"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "release_script"
test = false
bench = false

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
dunce = "1.0"
duration-string = "0.3"
flate2 = "1.0"
futures = "0.3"
futures-util = "0.3.28"
getset = "0.1.2"
glob = "0.3"
indicatif = "0.17.3"
lazy_static = "1.4"
log = "0.4"
mcping = { git = "https://github.com/Scetch/mcping.git", features = ["tokio-runtime"] }
regex = "1.8"
reqwest = { version = "0.11", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = { version = "0.12", features = ["paris", "termcolor"] }
time = { version = "0.3", features = ["formatting", "macros"] }
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
toml = "0.7"
walkdir = "2"
which = "4.4"
zip = "0.6"

[target.'cfg(not(windows))'.dependencies]
dirs = "5.0"
